export const CSV_COLUMNS = {
  FOLDER: '文件（访视层）',
  LEVEL1: '层级1（表单层）',
  DISPLAY_TYPE: '展示类型',
  LEVEL2_10: Array.from({ length: 9 }, (_, i) => `层级${i + 2}`),
  DATA_UNIT: '数据单位',
  OPTIONS: '可选项值',
  DATA_TYPE: '数据类型',
  GROUP_REPEATABLE: 'group是否可重复',
  TABLE_MULTI_ROW: 'table是否多行',
  IS_EXTRACTION_UNIT: '是否为抽取单位组',
  PRIMARY_SOURCES: '主要来源',
  SECONDARY_SOURCES: '次要来源',
  TIME_BINDING: '时间属性字段组绑定',
  IS_SENSITIVE: '是否为敏感字段',
  IS_PRIMARY: '是否为主键级字段',
  IS_EDITABLE: '字段是否可编辑',
  FIELD_DESC: '提示词-字段说明',
  EXTRACTION_PROMPT: '抽取提示词（示例）',
  CONFLICT_POLICY: '字段冲突处理规则',
  EXTENDED_CONFIG: '扩展配置',
  FIELD_UID: '字段UID',
  IS_NULLABLE: '字段可否为空（nullable）',
}

export const CSV_COLUMN_ALIASES = {
  FOLDER: ['文件夹', '文件（访视层）'],
  LEVEL1: ['层级1', '层级1（表单层）'],
  DISPLAY_TYPE: ['展示类型'],
  DATA_UNIT: ['数据单位'],
  OPTIONS: ['可选项值'],
  DATA_TYPE: ['数据类型'],
  GROUP_REPEATABLE: ['group是否可重复'],
  TABLE_MULTI_ROW: ['table是否多行'],
  IS_EXTRACTION_UNIT: ['是否为抽取单位组'],
  PRIMARY_SOURCES: ['主要来源', '主要来源（Primary Sources）'],
  SECONDARY_SOURCES: ['次要来源', '次要来源（Secondary Sources）'],
  TIME_BINDING: ['时间属性字段组绑定', '时间属性字段绑定（时间依赖字段）'],
  IS_SENSITIVE: ['是否为敏感字段', '是否为敏感字段（is_sensitive）'],
  IS_PRIMARY: ['是否为主键级字段'],
  IS_EDITABLE: ['字段是否可编辑', '字段是否可编辑（editable）'],
  FIELD_DESC: ['提示词-字段说明', '提示词- 字段说明'],
  EXTRACTION_PROMPT: ['抽取提示词（示例）', '抽取提示词'],
  CONFLICT_POLICY: ['字段冲突处理规则', '冲突处理规则'],
  EXTENDED_CONFIG: ['扩展配置', '扩展配置（JSON）'],
  FIELD_UID: ['字段UID', '字段UID（可选）'],
  IS_NULLABLE: ['字段可否为空（nullable）'],
}
