export const DISPLAY_TYPES = {
  TEXT: 'text',
  TEXTAREA: 'textarea',
  NUMBER: 'number',
  DATE: 'date',
  DATETIME: 'datetime',
  RADIO: 'radio',
  CHECKBOX: 'checkbox',
  SELECT: 'select',
  MULTISELECT: 'multiselect',
  FILE: 'file',
  GROUP: 'group',
  TABLE: 'table',
  MULTI_TEXT: 'multi_text',
  SLIDER: 'slider',
  CASCADER: 'cascader',
  MATRIX_RADIO: 'matrix_radio',
  MATRIX_CHECKBOX: 'matrix_checkbox',
  PARAGRAPH: 'paragraph',
  DIVIDER: 'divider',
  RANDOMIZATION: 'randomization',
}

export const BASIC_DISPLAY_TYPES = [
  DISPLAY_TYPES.TEXT,
  DISPLAY_TYPES.TEXTAREA,
  DISPLAY_TYPES.NUMBER,
  DISPLAY_TYPES.DATE,
  DISPLAY_TYPES.DATETIME,
  DISPLAY_TYPES.RADIO,
  DISPLAY_TYPES.CHECKBOX,
  DISPLAY_TYPES.SELECT,
  DISPLAY_TYPES.MULTISELECT,
  DISPLAY_TYPES.FILE,
  DISPLAY_TYPES.TABLE,
  DISPLAY_TYPES.PARAGRAPH,
  DISPLAY_TYPES.DIVIDER,
]

export const RESTRICTED_DISPLAY_TYPES = [
  DISPLAY_TYPES.MULTI_TEXT,
  DISPLAY_TYPES.SLIDER,
  DISPLAY_TYPES.CASCADER,
  DISPLAY_TYPES.MATRIX_RADIO,
  DISPLAY_TYPES.MATRIX_CHECKBOX,
  DISPLAY_TYPES.RANDOMIZATION,
]

export const DISPLAY_TYPE_CONFIG = {
  [DISPLAY_TYPES.TEXT]: {
    label: '文本',
    icon: 'FontSizeOutlined',
    category: 'fill',
    dataType: 'string',
    supportOptions: false,
  },
  [DISPLAY_TYPES.TEXTAREA]: {
    label: '多行文本',
    icon: 'FileTextOutlined',
    category: 'fill',
    dataType: 'string',
    supportOptions: false,
  },
  [DISPLAY_TYPES.NUMBER]: {
    label: '数字',
    icon: 'NumberOutlined',
    category: 'fill',
    dataType: 'number',
    supportOptions: false,
  },
  [DISPLAY_TYPES.DATE]: {
    label: '日期',
    icon: 'CalendarOutlined',
    category: 'fill',
    dataType: 'string',
    format: 'date',
    supportOptions: false,
  },
  [DISPLAY_TYPES.DATETIME]: {
    label: '日期时间',
    icon: 'CalendarOutlined',
    category: 'fill',
    dataType: 'string',
    format: 'date-time',
    supportOptions: false,
  },
  [DISPLAY_TYPES.RADIO]: {
    label: '单选',
    icon: 'CheckCircleOutlined',
    category: 'select',
    dataType: 'string',
    supportOptions: true,
    displayMode: 'expanded',
  },
  [DISPLAY_TYPES.CHECKBOX]: {
    label: '多选',
    icon: 'CheckSquareOutlined',
    category: 'select',
    dataType: 'array',
    supportOptions: true,
    displayMode: 'expanded',
  },
  [DISPLAY_TYPES.SELECT]: {
    label: '下拉单选',
    icon: 'DownOutlined',
    category: 'select',
    dataType: 'string',
    supportOptions: true,
    displayMode: 'dropdown',
  },
  [DISPLAY_TYPES.MULTISELECT]: {
    label: '下拉多选',
    icon: 'CheckSquareOutlined',
    category: 'select',
    dataType: 'array',
    supportOptions: true,
    displayMode: 'dropdown',
  },
  [DISPLAY_TYPES.FILE]: {
    label: '文件',
    icon: 'UploadOutlined',
    category: 'file',
    dataType: 'string',
    supportOptions: false,
  },
  [DISPLAY_TYPES.GROUP]: {
    label: '分组',
    icon: 'FolderOutlined',
    category: 'auxiliary',
    isContainer: true,
  },
  [DISPLAY_TYPES.TABLE]: {
    label: '表格',
    icon: 'TableOutlined',
    category: 'auxiliary',
    isContainer: true,
  },
  [DISPLAY_TYPES.MULTI_TEXT]: {
    label: '多项填空',
    icon: 'FontSizeOutlined',
    category: 'fill',
    supportOptions: false,
  },
  [DISPLAY_TYPES.SLIDER]: {
    label: '滑块评分',
    icon: 'MinusOutlined',
    category: 'select',
    supportOptions: false,
    requireConfig: true,
  },
  [DISPLAY_TYPES.CASCADER]: {
    label: '级联选择',
    icon: 'ApartmentOutlined',
    category: 'select',
    supportOptions: false,
    requireConfig: true,
  },
  [DISPLAY_TYPES.MATRIX_RADIO]: {
    label: '矩阵单选',
    icon: 'BorderOutlined',
    category: 'matrix',
    supportOptions: false,
    requireConfig: true,
  },
  [DISPLAY_TYPES.MATRIX_CHECKBOX]: {
    label: '矩阵多选',
    icon: 'DotChartOutlined',
    category: 'matrix',
    supportOptions: false,
    requireConfig: true,
  },
  [DISPLAY_TYPES.PARAGRAPH]: {
    label: '段落说明',
    icon: 'AlignLeftOutlined',
    category: 'auxiliary',
    isReadOnly: true,
  },
  [DISPLAY_TYPES.DIVIDER]: {
    label: '分割线',
    icon: 'MinusOutlined',
    category: 'auxiliary',
    isReadOnly: true,
  },
  [DISPLAY_TYPES.RANDOMIZATION]: {
    label: '随机化分组',
    icon: 'ShuffleOutlined',
    category: 'auxiliary',
    requireConfig: true,
  },
}

export const COMPONENT_CATEGORIES = {
  FILL: {
    key: 'fill',
    label: '填空',
    icon: 'EditOutlined',
    types: [
      DISPLAY_TYPES.TEXT,
      DISPLAY_TYPES.TEXTAREA,
      DISPLAY_TYPES.NUMBER,
      DISPLAY_TYPES.DATE,
      DISPLAY_TYPES.DATETIME,
      DISPLAY_TYPES.MULTI_TEXT,
    ],
  },
  SELECT: {
    key: 'select',
    label: '选择',
    icon: 'CheckSquareOutlined',
    types: [
      DISPLAY_TYPES.RADIO,
      DISPLAY_TYPES.CHECKBOX,
      DISPLAY_TYPES.SELECT,
      DISPLAY_TYPES.MULTISELECT,
      DISPLAY_TYPES.SLIDER,
      DISPLAY_TYPES.CASCADER,
    ],
  },
  MATRIX: {
    key: 'matrix',
    label: '矩阵',
    icon: 'BorderOutlined',
    types: [DISPLAY_TYPES.MATRIX_RADIO, DISPLAY_TYPES.MATRIX_CHECKBOX],
  },
  FILE: {
    key: 'file',
    label: '文件',
    icon: 'UploadOutlined',
    types: [DISPLAY_TYPES.FILE],
  },
  CONTAINER: {
    key: 'container',
    label: '容器',
    icon: 'AppstoreOutlined',
    types: [DISPLAY_TYPES.GROUP, DISPLAY_TYPES.TABLE],
  },
  AUXILIARY: {
    key: 'auxiliary',
    label: '辅助',
    icon: 'LineOutlined',
    types: [DISPLAY_TYPES.PARAGRAPH, DISPLAY_TYPES.DIVIDER, DISPLAY_TYPES.RANDOMIZATION],
  },
}
