import {
  assignTemplateToProject,
  getCRFCategories,
  getCRFTemplate,
  getCRFTemplates,
  getCrfDocTypes,
  getProjectTemplate,
  updateCrfTemplateMeta,
} from './crfTemplate/basicApi'
import {
  cloneCrfTemplate,
  createCrfTemplateDesigner,
  deleteCrfTemplate,
  getCrfTemplateProjectUsage,
  importCrfTemplateFromCsv,
  publishCrfTemplate,
  saveCrfTemplateDesigner,
} from './crfTemplate/designerApi'
import {
  activateCrfTemplateVersion,
  convertTemplate,
  getCrfTemplateVersion,
  listCrfTemplateVersions,
} from './crfTemplate/versionsApi'

export {
  activateCrfTemplateVersion,
  assignTemplateToProject,
  cloneCrfTemplate,
  convertTemplate,
  createCrfTemplateDesigner,
  deleteCrfTemplate,
  getCRFCategories,
  getCRFTemplate,
  getCRFTemplates,
  getCrfDocTypes,
  getCrfTemplateProjectUsage,
  getCrfTemplateVersion,
  getProjectTemplate,
  importCrfTemplateFromCsv,
  listCrfTemplateVersions,
  publishCrfTemplate,
  saveCrfTemplateDesigner,
  updateCrfTemplateMeta,
}

export default {
  getCRFTemplates,
  getCRFTemplate,
  updateCrfTemplateMeta,
  getCRFCategories,
  getCrfDocTypes,
  assignTemplateToProject,
  getProjectTemplate,
  convertTemplate,
  importCrfTemplateFromCsv,
  publishCrfTemplate,
  saveCrfTemplateDesigner,
  createCrfTemplateDesigner,
  cloneCrfTemplate,
  getCrfTemplateProjectUsage,
  deleteCrfTemplate,
  listCrfTemplateVersions,
  getCrfTemplateVersion,
  activateCrfTemplateVersion,
}
