import {
  addProjectMember,
  createProject,
  deleteProject,
  getProject,
  getProjectMembers,
  getProjects,
  removeProjectMember,
  toggleProjectStatus,
  updateProject,
} from './project/projectsApi'
import {
  enrollPatient,
  fetchProjectPatientsCrfGroupFields,
  getProjectPatientDetail,
  getProjectPatients,
  removeProjectPatient,
} from './project/patientsApi'
import { getProjectPatientCrf } from './project/patientData'
import {
  createProjectCrfRecordInstance,
  deleteProjectCrfFieldValue,
  deleteProjectCrfRecordInstance,
  getCrfFieldEvidence,
  getProjectCrfFieldCandidates,
  getProjectCrfFieldHistory,
  getProjectPatientCrfConflicts,
  resolveAllProjectPatientCrfConflicts,
  resolveProjectPatientCrfConflict,
  saveProjectCrfFieldValue,
  selectProjectCrfFieldCandidate,
  updateProjectPatientCrfFields,
} from './project/crfFieldsApi'
import {
  getCrfExtractionProgress,
  listProjectActiveExtractionBatches,
  startCrfExtraction,
  updateProjectCrfFolder,
  updateProjectCrfFolderBatch,
} from './project/extractionApi'
import {
  applyTemplateVersion,
  exportProjectCrfFile,
  getProjectTemplateDesigner,
  saveProjectTemplateDesigner,
} from './project/templateApi'

export {
  addProjectMember,
  applyTemplateVersion,
  createProject,
  createProjectCrfRecordInstance,
  deleteProject,
  deleteProjectCrfFieldValue,
  deleteProjectCrfRecordInstance,
  enrollPatient,
  exportProjectCrfFile,
  fetchProjectPatientsCrfGroupFields,
  getCrfExtractionProgress,
  getCrfFieldEvidence,
  getProject,
  getProjectCrfFieldCandidates,
  getProjectCrfFieldHistory,
  getProjectMembers,
  getProjectPatientCrf,
  getProjectPatientCrfConflicts,
  getProjectPatientDetail,
  getProjectPatients,
  getProjectTemplateDesigner,
  getProjects,
  listProjectActiveExtractionBatches,
  removeProjectMember,
  removeProjectPatient,
  resolveAllProjectPatientCrfConflicts,
  resolveProjectPatientCrfConflict,
  saveProjectCrfFieldValue,
  saveProjectTemplateDesigner,
  selectProjectCrfFieldCandidate,
  startCrfExtraction,
  toggleProjectStatus,
  updateProject,
  updateProjectCrfFolder,
  updateProjectCrfFolderBatch,
  updateProjectPatientCrfFields,
}

export default {
  getProjects,
  getProject,
  createProject,
  updateProject,
  deleteProject,
  toggleProjectStatus,
  getProjectMembers,
  addProjectMember,
  removeProjectMember,
  getProjectPatients,
  getProjectPatientDetail,
  updateProjectPatientCrfFields,
  getProjectPatientCrfConflicts,
  resolveProjectPatientCrfConflict,
  resolveAllProjectPatientCrfConflicts,
  getProjectCrfFieldHistory,
  getProjectCrfFieldCandidates,
  saveProjectCrfFieldValue,
  deleteProjectCrfFieldValue,
  createProjectCrfRecordInstance,
  deleteProjectCrfRecordInstance,
  selectProjectCrfFieldCandidate,
  updateProjectCrfFolder,
  updateProjectCrfFolderBatch,
  enrollPatient,
  removeProjectPatient,
  startCrfExtraction,
  getCrfExtractionProgress,
  listProjectActiveExtractionBatches,
  getProjectTemplateDesigner,
  saveProjectTemplateDesigner,
  applyTemplateVersion,
  exportProjectCrfFile,
}
