import { lazy } from 'react'

export const Dashboard = lazy(() => import('../pages/Dashboard'))
export const DocumentUpload = lazy(() => import('../pages/DocumentUpload'))
export const AIProcessing = lazy(() => import('../pages/AIProcessing'))
export const CRFDesigner = lazy(() => import('../pages/CRFDesigner'))
export const PatientPool = lazy(() => import('../pages/PatientPool'))
export const ResearchProjectsEntry = lazy(() => import('../pages/ResearchDataset/ResearchProjectsEntry'))
export const ProjectDatasetView = lazy(() => import('../pages/ResearchDataset/ProjectDatasetView'))
export const ProjectPatientDetail = lazy(() => import('../pages/ResearchDataset/ProjectPatientDetail'))
export const ProjectTemplateDesigner = lazy(() => import('../pages/ResearchDataset/ProjectTemplateDesigner'))
export const PatientDetail = lazy(() => import('../pages/PatientDetail'))
export const UserProfile = lazy(() => import('../pages/UserSystem/UserProfile'))
export const SystemSettings = lazy(() => import('../pages/UserSystem/SystemSettings'))
export const Login = lazy(() => import('../pages/UserSystem/Login'))
export const ExtractionV2 = lazy(() => import('../pages/ExtractionV2'))
export const FileList = lazy(() => import('../pages/FileList'))
export const ExtractionDebugger = lazy(() => import('../pages/ExtractionDebugger'))
export const Admin = lazy(() => import('../pages/Admin'))
