import { useMemo } from 'react'
import { buildFileListColumns } from './tableColumns'

export const useFileListColumns = ({
  columnFilters,
  columnWidths,
  FilterIcon,
  handleAiMatchPatient,
  handleArchivePatient,
  handleConfirmRecommendedArchive,
  handleCreatePatientFromDoc,
  handleDeleteDocument,
  handleDownload,
  handleParseDocument,
  handleUnbindDocument,
  matchingDocIds,
  pollingParseIds,
  renderGroupRow,
  renderResizableColumnTitle,
  SortIcon,
  startingParseIds,
  viewMode,
}) => (
  useMemo(() => buildFileListColumns({
    columnFilters,
    columnWidths,
    FilterIcon,
    handleAiMatchPatient,
    handleArchivePatient,
    handleConfirmRecommendedArchive,
    handleCreatePatientFromDoc,
    handleDeleteDocument,
    handleDownload,
    handleParseDocument,
    handleUnbindDocument,
    matchingDocIds,
    pollingParseIds,
    renderGroupRow,
    renderResizableColumnTitle,
    SortIcon,
    startingParseIds,
    viewMode,
  }), [
    columnFilters,
    columnWidths,
    FilterIcon,
    handleAiMatchPatient,
    handleArchivePatient,
    handleConfirmRecommendedArchive,
    handleCreatePatientFromDoc,
    handleDeleteDocument,
    handleDownload,
    handleParseDocument,
    handleUnbindDocument,
    matchingDocIds,
    pollingParseIds,
    renderGroupRow,
    renderResizableColumnTitle,
    SortIcon,
    startingParseIds,
    viewMode,
  ])
)
