export const useFileListShellProps = ({
  batchActions,
  columnFilters,
  columns,
  dataSources,
  documentActions,
  filters,
  groupActions,
  groupRenderers,
  isGroupSplitterDragging,
  isGroupSplitterHover,
  message,
  modalState,
  patientMatchActions,
  patientGroupPanelWidth,
  refreshAll,
  remoteData,
  selectedRowKeys,
  setColumnFilters,
  setIsGroupSplitterHover,
  setSelectedRowKeys,
  token,
  uploadState,
  viewMode,
  tableState,
}) => ({
  filterProps: {
    ...filters,
    availableFileTypeCategories: dataSources.availableFileTypeCategories,
    availableStatusInfoOptions: dataSources.availableStatusInfoOptions,
    availableTaskStatusOptions: dataSources.availableTaskStatusOptions,
  },
  toolbarProps: {
    ...batchActions,
    batchDeleteLoading: modalState.batchDeleteLoading,
    columnFilters,
    handleBatchDelete: documentActions.handleBatchDelete,
    handleViewModeChange: filters.handleViewModeChange,
    message,
    refreshAll,
    selectedRowKeys,
    setColumnFilters,
    setPagination: remoteData.setPagination,
    setSelectedRowKeys,
    setUploadModalVisible: uploadState.setUploadModalVisible,
    token,
    treeLoading: remoteData.treeLoading,
    viewMode,
  },
  contentProps: {
    ...tableState,
    columns,
    displayDataSource: dataSources.displayDataSource,
    fileListLoading: remoteData.fileListLoading,
    isGroupSplitterDragging,
    isGroupSplitterHover,
    patientGroupList: dataSources.patientGroupList,
    patientGroupPanelWidth,
    renderPatientGroupCard: groupRenderers.renderPatientGroupCard,
    setIsGroupSplitterHover,
    tablePagination: dataSources.tablePagination,
    token,
    viewMode,
  },
  uploadProps: uploadState,
  modalsProps: {
    ...batchActions,
    ...groupActions,
    ...modalState,
    ...patientMatchActions,
    detailRefreshTrigger: documentActions.detailRefreshTrigger,
    handleDetailModalClose: documentActions.handleDetailModalClose,
    handleReExtract: documentActions.handleReExtract,
    message,
    refreshAll,
    setSelectedRowKeys,
    token,
  },
})
