import { dispatchRequestPatientCreate } from '../../../utils/createIntentEvents'
import {
  COLUMN_OPTIONS,
  DIAGNOSIS_OPTIONS,
} from './patientPoolConstants'

export const usePatientPoolPageProps = ({
  addPatient,
  advancedFilterForm,
  advancedFilters,
  batchImport,
  batchImportVisible,
  columnWidths,
  columns,
  departmentLoading,
  departmentTreeData,
  exportFlow,
  filters,
  getDepartmentNameById,
  handleApplyAdvancedFilters,
  handleBatchAction,
  handleResetAdvancedFilters,
  handleResetFilters,
  handleResize,
  handleTableChange,
  importDetail,
  loading,
  pagination,
  patientData,
  selectedRowKeys,
  setAdvancedFilterVisible,
  setBatchImportVisible,
  setExportModalVisible,
  setPatientDetailVisible,
  setSelectedRowKeys,
  setStatisticsCollapsed,
  setViewingPatientDetail,
  setVisibleColumns,
  statistics,
  statisticsCollapsed,
  toolbar,
  visibleColumns,
}) => ({
  statisticsProps: {
    statistics,
    collapsed: statisticsCollapsed,
    onToggle: () => setStatisticsCollapsed(!statisticsCollapsed),
  },
  filterToolbarProps: {
    filters,
    advancedFilters,
    departmentLoading,
    departmentTreeData,
    visibleColumns,
    columnOptions: COLUMN_OPTIONS,
    patientCount: patientData.length,
    totalCount: pagination.total,
    onSearch: toolbar.debounceSearch,
    onFiltersChange: toolbar.setFilters,
    onPageReset: toolbar.resetPaginationPage,
    onResetFilters: handleResetFilters,
    onOpenAdvancedFilters: () => setAdvancedFilterVisible(true),
    onVisibleColumnsChange: setVisibleColumns,
  },
  listCardProps: {
    selectedRowKeys,
    patientData,
    pagination,
    columns,
    visibleColumns,
    columnWidths,
    batchActions: toolbar.batchActions,
    loading,
    onSelectRows: setSelectedRowKeys,
    onBatchAction: handleBatchAction,
    onAddPatient: () => dispatchRequestPatientCreate(),
    onBatchImport: () => setBatchImportVisible(true),
    onTableChange: handleTableChange,
    onResize: handleResize,
  },
  modalsProps: {
    advancedFilter: {
      open: toolbar.filterVisible,
      form: advancedFilterForm,
      advancedFilters,
      onCancel: () => setAdvancedFilterVisible(false),
      onReset: handleResetAdvancedFilters,
      onApply: handleApplyAdvancedFilters,
    },
    exportModal: {
      open: toolbar.exportModalVisible,
      loading: exportFlow.exportLoading,
      form: exportFlow.exportForm,
      selectedCount: selectedRowKeys.length,
      filters,
      advancedFilters,
      onCancel: () => setExportModalVisible(false),
      onExport: exportFlow.handleExport,
      onChange: (patch) => exportFlow.setExportForm((prev) => ({ ...prev, ...patch })),
    },
    addPatient: {
      open: addPatient.addPatientVisible,
      isEditing: addPatient.isEditingPatient,
      step: addPatient.addPatientStep,
      form: addPatient.addPatientForm,
      loading: addPatient.addPatientLoading,
      diagnosisOptions: DIAGNOSIS_OPTIONS,
      departmentLoading,
      departmentTreeData,
      getDepartmentNameById,
      onCancel: addPatient.closeAddPatientModal,
      onPrev: addPatient.goPrevAddPatientStep,
      onNext: addPatient.handleAddPatient,
    },
    batchImport: {
      open: batchImportVisible,
      step: batchImport.batchImportStep,
      importData: batchImport.importData,
      selectedKeys: batchImport.selectedImportKeys,
      uploadProps: batchImport.uploadProps,
      loading: batchImport.importLoading,
      onCancel: batchImport.closeBatchImportModal,
      onPrev: batchImport.goPrevBatchImportStep,
      onNext: batchImport.handleBatchImport,
      onDownloadTemplate: batchImport.downloadTemplate,
      onSelectKeys: batchImport.setSelectedImportKeys,
      onViewPatient: (record) => {
        setViewingPatientDetail(record)
        setPatientDetailVisible(true)
      },
    },
    importPatientDetail: {
      open: importDetail.patientDetailVisible,
      patient: importDetail.viewingPatientDetail,
      onClose: importDetail.closeImportPatientDetailModal,
    },
  },
})
