import { appThemeToken } from '../../../styles/themeTokens'

export const styles = {
  container: {
    display: 'flex',
    width: '100%',
    minHeight: '100vh',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', 'PingFang SC', 'Hiragino Sans GB', 'Microsoft YaHei', sans-serif",
    background: appThemeToken.colorBgLayout,
  },
  loginPanel: {
    width: 440,
    background: 'white',
    padding: '50px 50px 30px',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: '-2px 0 20px rgba(0, 0, 0, 0.06)',
    position: 'relative',
    zIndex: 10,
  },
  loginHeader: {
    marginBottom: 30,
  },
  registerLink: {
    textAlign: 'right',
    marginBottom: 24,
  },
  link: {
    color: appThemeToken.colorPrimary,
    textDecoration: 'none',
    fontSize: 14,
    fontWeight: 500,
  },
  loginTabs: {
    display: 'flex',
    borderBottom: `1px solid ${appThemeToken.colorBorder}`,
  },
  tab: {
    flex: 1,
    padding: '14px 0',
    textAlign: 'center',
    fontSize: 16,
    color: appThemeToken.colorTextSecondary,
    cursor: 'pointer',
    borderBottomWidth: '2px',
    borderBottomStyle: 'solid',
    borderBottomColor: 'transparent',
    transition: 'all 0.3s ease',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  tabActive: {
    color: appThemeToken.colorPrimary,
    borderBottomColor: appThemeToken.colorPrimary,
    fontWeight: 500,
  },
  qrSection: {
    textAlign: 'center',
    padding: '20px 0 30px',
    flex: 1,
  },
  qrContainer: {
    width: 220,
    height: 220,
    margin: '0 auto 24px',
    background: 'rgba(0, 0, 0, 0.02)',
    border: `1px solid ${appThemeToken.colorBorder}`,
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  qrLoading: {
    textAlign: 'center',
  },
  qrExpired: {
    textAlign: 'center',
    padding: 20,
  },
  qrExpiredText: {
    color: appThemeToken.colorTextSecondary,
    fontSize: 14,
  },
  qrImage: {
    width: '100%',
    height: '100%',
    padding: 15,
    objectFit: 'contain',
  },
  qrTips: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: appThemeToken.colorText,
    fontSize: 16,
    fontWeight: 500,
    marginBottom: 8,
  },
  qrSubTips: {
    color: appThemeToken.colorTextSecondary,
    fontSize: 14,
  },
  emailSection: {
    padding: '20px 0 10px',
    flex: 1,
  },
  registerSection: {
    padding: '10px 0 10px',
    flex: 1,
  },
  registerTitle: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    fontWeight: 500,
    color: appThemeToken.colorText,
    padding: '14px 0',
    borderBottom: `2px solid ${appThemeToken.colorPrimary}`,
  },
  registerTips: {
    textAlign: 'center',
    fontSize: 14,
    color: appThemeToken.colorTextSecondary,
    marginTop: 16,
  },
  input: {
    height: 46,
    borderRadius: 8,
    fontSize: 14,
  },
  emailWithCodeRow: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
  },
  emailInput: {
    height: 46,
    borderRadius: 8,
    fontSize: 14,
    flex: 1,
  },
  sendCodeButton: {
    borderRadius: 999,
    padding: '0 18px',
    fontSize: 14,
    fontWeight: 500,
  },
  formOptions: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  forgotLink: {
    color: appThemeToken.colorPrimary,
    fontSize: 14,
    textDecoration: 'none',
  },
  loginButton: {
    height: 46,
    borderRadius: 8,
    fontSize: 16,
    fontWeight: 500,
    background: `linear-gradient(135deg, ${appThemeToken.colorPrimary} 0%, rgba(24, 144, 255, 0.82) 100%)`,
    border: 'none',
  },
  divider: {
    height: 1,
    background: appThemeToken.colorBorder,
    margin: '20px 0',
    position: 'relative',
  },
  dividerText: {
    position: 'absolute',
    left: '50%',
    top: '50%',
    transform: 'translate(-50%, -50%)',
    background: 'white',
    padding: '0 16px',
    color: appThemeToken.colorTextSecondary,
    fontSize: 12,
  },
  otherMethods: {
    display: 'flex',
    justifyContent: 'center',
    marginBottom: 24,
  },
  otherMethodItem: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: 8,
    cursor: 'pointer',
    color: appThemeToken.colorTextSecondary,
    fontSize: 14,
    transition: 'color 0.3s',
    padding: '8px 16px',
  },
  otherMethodIcon: {
    width: 44,
    height: 44,
    borderRadius: 10,
    background: 'rgba(24, 144, 255, 0.08)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    transition: 'all 0.3s',
  },
}
